assetic:
    bundles:
        - MMCmfAdminBundle
        - FOSUserBundle
    assets:
        mm_cmf_admin_assets_less:
            filters:
                  - 'less'
            inputs:
                  - '@MMCmfAdminBundle/Resources/less/mmcmfadmin.base.less'
                  - '@MMCmfAdminBundle/Resources/less/mmcmflogin.less'

        mm_cmf_admin_assets_js:
            inputs:
                  - '@MMCmfAdminBundle/Resources/public/vendor/jquery/dist/jquery.min.js'
                  - '@MMCmfAdminBundle/Resources/public/vendor/AdminLTE/bootstrap/js/bootstrap.min.js'
                  - '@MMCmfAdminBundle/Resources/public/vendor/AdminLTE/dist/js/app.js'
                  - '@MMCmfAdminBundle/Resources/public/js/notify.js'
                  - '@MMCmfAdminBundle/Resources/public/js/MMCmfAdmin.js'
                  - '@MMCmfAdminBundle/Resources/public/js/MMCmfAdminEditFrame.js'
                  - '@MMCmfAdminBundle/Resources/public/js/core.js'
        mm_cmf_admin_assets_css:
            inputs:
                  - '@MMCmfAdminBundle/Resources/public/vendor/AdminLTE/bootstrap/css/bootstrap.min.css'
                  - "@MMCmfAdminBundle/Resources/public/vendor/AdminLte/dist/css/AdminLTE.min.css"
                  - '@MMCmfAdminBundle/Resources/public/vendor/AdminLte/dist/css/skins/skin-blue.min.css'

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: MandarinMedien\MMCmfAdminBundle\Entity\User

    profile:
        form:
            type: MandarinMedien\MMCmfAdminBundle\Form\UserType

twig:
    globals:
        widget_manager: @mm_cmf_admin.widget_manager
    form:
        resources: ['bootstrap_3_layout.html.twig']

monolog:
    handlers:
        console:
            type: stream
            level: error

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/admin/user, role: ROLE_ADMIN }
        - { path: ^/admin/roles, role: ROLE_ADMIN }
