imports:
    - { resource: 'config_core.yml' }

twig:
    form:
        resources:
            - bootstrap_3_layout.html.twig
            - MMCmfAdminBundle:Form:menu.html.twig
            - MMCmfAdminBundle:Form:form.base.html.twig
            - MMCmfAdminBundle:Form:noderoute.inline.html.twig

security:
    firewalls:
        main:
            form_login:
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4