imports:
    - { resource: 'config_core.yml' }

twig:
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "MMCmfAdminBundle:Form:menu.html.twig"
        - "MMCmfAdminBundle:Form:form.base.html.twig"
        - "MMCmfAdminBundle:Form:noderoute.inline.html.twig"

fos_user:
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"