mm_cmf_admin_user:
    resource: "@MMCmfAdminBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user


mm_cmf_admin_menu:
    path:     /admin/menu
    defaults: { _controller: MMCmfAdminBundle:CmfAdminMenu:index }

mm_cmf_admin_menu_new:
    path:     /admin/menu/new
    defaults: { _controller: MMCmfAdminBundle:CmfAdminMenu:new }

mm_cmf_admin_menu_create:
    path:     /admin/menu/create
    defaults: { _controller: MMCmfAdminBundle:CmfAdminMenu:create }

mm_cmf_admin_menu_edit:
    path:     /admin/menu/{id}/edit
    defaults: { _controller: MMCmfAdminBundle:CmfAdminMenu:edit }

mm_cmf_admin_menu_update:
    path:     /admin/menu/{id}/update
    defaults: { _controller: MMCmfAdminBundle:CmfAdminMenu:update }

mm_cmf_admin_menu_delete:
    path:     /admin/menu/{id}/delete
    defaults: { _controller: MMCmfAdminBundle:CmfAdminMenu:delete }


mm_cmf_admin_noderoute:
    path:     /admin/route
    defaults: { _controller: MMCmfAdminBundle:CmfAdminNodeRoute:index }

mm_cmf_admin_noderoute_new:
    path:     /admin/route/{node_route_type}/new
    defaults: { _controller: MMCmfAdminBundle:CmfAdminNodeRoute:new, node_route_type: 'alias' }

mm_cmf_admin_noderoute_create:
    path:     /admin/route/{node_route_type}/create
    defaults: { _controller: MMCmfAdminBundle:CmfAdminNodeRoute:create, node_route_type: 'alias' }

mm_cmf_admin_noderoute_edit:
    path:     /admin/route/{id}/edit
    defaults: { _controller: MMCmfAdminBundle:CmfAdminNodeRoute:edit }

mm_cmf_admin_noderoute_update:
    path:     /admin/route/{id}/update
    defaults: { _controller: MMCmfAdminBundle:CmfAdminNodeRoute:update }

mm_cmf_admin_noderoute_delete:
    path:     /admin/route/{id}/delete
    defaults: { _controller: MMCmfAdminBundle:CmfAdminNodeRoute:delete }


mm_cmf_admin_page:
    path:     /admin/page
    defaults: { _controller: MMCmfAdminBundle:CmfAdminPage:index }

mm_cmf_admin_page_new:
    path:     /admin/page/new/
    defaults: { _controller: MMCmfAdminBundle:CmfAdminPage:new }

mm_cmf_admin_page_delete:
    path:     /admin/page/{id}/delete
    defaults: { _controller: MMCmfAdminBundle:CmfAdminPage:delete }

mm_cmf_admin_page_create:
    path:     /admin/page/create
    defaults: { _controller: MMCmfAdminBundle:CmfAdminPage:create }

mm_cmf_admin_page_edit:
    path:     /admin/page/{id}/edit
    defaults: { _controller: MMCmfAdminBundle:CmfAdminPage:edit }

mm_cmf_admin_page_update:
    path:     /admin/page/{id}/update
    defaults: { _controller: MMCmfAdminBundle:CmfAdminPage:update }


mm_cmf_admin_contentnode:
    path:     /admin/contentnode
    defaults: { _controller: MMCmfAdminBundle:CmfAdminContentNode:index}

mm_cmf_admin_contentnode_new:
    path:     /admin/contentnode/{contentnode_type}/new
    defaults:
        _controller: MMCmfAdminBundle:CmfAdminContentNode:new
        contentnode_type: 'contentnode'

mm_cmf_admin_contentnode_create:
    path:     /admin/contentnode/{contentnode_type}/create
    defaults:
        _controller: MMCmfAdminBundle:CmfAdminContentNode:create
        contentnode_type: 'contentnode'

mm_cmf_admin_contentnode_edit:
    path:     /admin/contentnode/{id}/edit
    defaults: { _controller: MMCmfAdminBundle:CmfAdminContentNode:edit }

mm_cmf_admin_contentnode_update:
    path:     /admin/contentnode/{id}/update
    defaults: { _controller: MMCmfAdminBundle:CmfAdminContentNode:update }

mm_cmf_admin_contentnode_delete:
    path:     /admin/contentnode/{id}/delete
    defaults: { _controller: MMCmfAdminBundle:CmfAdminContentNode:delete }


mm_cmf_admin_homepage_empty:
    path: /admin/empty
    defaults: {_controller: MMCmfAdminBundle:CmfAdmin:empty}


mm_cmf_admin_visibilty_toggle:
    path: /admin/visibilty/{id}/toggle
    defaults: {_controller: MMCmfAdminBundle:CmfAdmin:toggleVisibility}


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /admin/profile

mm_cmf_admin_homepage:
    path:     /admin
    defaults: { _controller: MMCmfAdminBundle:CmfAdmin:dashboard }

mm_cmf_admin_live_edit:
    path: /admin/liveedit/{route}
    defaults: {_controller: MMCmfAdminBundle:CmfAdmin:liveEdit, route: null}



