services:

    ### WIDGET CONFIGURATION ####
    mm_cmf_admin.widget_manager:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget\WidgetManager

    mm_cmf_admin.widget_factory:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget\WidgetFactory
        arguments: [@mm_cmf_admin.widget_manager]


    mm_cmf_admin.twig_widget_extension:
        class: MandarinMedien\MMCmfAdminBundle\Twig\WidgetRenderExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension }

    mm_cmf_admin.admin_content_group:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget\Type\LinkGroupWidget
        factory: ["@mm_cmf_admin.widget_factory", createGroupWidget]
        arguments: ["Seiten und Inhalte", "file-text-o"]
        tags:
          - {name: mm_cmf_admin.admin_widget}

    mm_cmf_admin.admin_edit:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Liveedit", "mm_cmf_admin_homepage", "edit"]
        tags:
          - {name: mm_cmf_admin.admin_content_group}

    mm_cmf_admin.admin_pages:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Seiten", "mm_cmf_admin_page", "file-o"]
        tags:
          - {name: mm_cmf_admin.admin_content_group}

    mm_cmf_admin.admin_contentnodes:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Inhalte", "mm_cmf_admin_contentnode", "align-left"]
        tags:
          - {name: mm_cmf_admin.admin_content_group}


    mm_cmf_admin.admin_navigation_group:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget\Type\LinkGroupWidget
        factory: ["@mm_cmf_admin.widget_factory", createGroupWidget]
        arguments: ["Links und Navigation", "globe"]
        tags:
          - {name: mm_cmf_admin.admin_widget}

    mm_cmf_admin.admin_routes:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Routen", "mm_cmf_admin_noderoute", "link"]
        tags:
          - {name: mm_cmf_admin.admin_navigation_group}

    mm_cmf_admin.admin_menus:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Menus", "mm_cmf_admin_menu", "bars"]
        tags:
          - {name: mm_cmf_admin.admin_navigation_group}

    mm_cmf_admin.admin_user_group:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget\Type\LinkGroupWidget
        factory: ["@mm_cmf_admin.widget_factory", createGroupWidget]
        arguments: ["Benutzerverwaltung", "group"]
        tags:
          - {name: mm_cmf_admin.admin_widget}

    mm_cmf_admin.admin_user:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Benutzer", "mm_cmf_admin_user", "user"]
        tags:
             - {name: mm_cmf_admin.admin_user_group}


    mm_cmf_admin.admin_roles:
        class: MandarinMedien\MMCmfAdminBundle\Admin\Widget
        factory: ["@mm_cmf_admin.widget_factory", createWidget]
        arguments: ["Rollen", "mm_cmf_admin_menu", "cog"]
        tags:
             - {name: mm_cmf_admin.admin_user_group}

    mm_cmf_admin.form_type.entity_hidden:
        class: MandarinMedien\MMCmfAdminBundle\Form\Types\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {name: form.type, alias: entity_hidden}

    mm_cmf_admin.form_type.content_node:
        class: MandarinMedien\MMCmfAdminBundle\Form\ContentNodeType
        arguments: [@service_container]
        tags:
            - {name: form.type, alias: mm_cmf_admin_content_node}


    ### USERCONFIGURATION ###

    mm_cmf_admin.user_profile:
        class: MandarinMedien\MMCmfAdminBundle\Form\UserType
        tags:
            - {name: form.type, alias: app_user_edit}
