<?php

namespace MandarinMedien\MMCmfAdminBundle\Controller;

use MandarinMedien\MMCmfAdminBundle\Response\JsonFormResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Response;

class CmfAdminBaseController extends Controller
{

    /**
     * render function
     * sets the template to extend from
     *
     * {@inheritdoc}
     */
    public function render($view, array $parameters = array(), Response $response = null)
    {
        if($this->get('request')->isXmlHttpRequest())
        {
            $parameters['extends_from'] = 'MMCmfAdminBundle:Admin:admin.xhr.html.twig';
        }  else {
            $parameters['extends_from'] = 'MMCmfAdminBundle:Admin:admin.html.twig';
        }

        return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
    }


    /**
     * default response for Form Actions
     * returns either JsonFormResponse on XHR Request or RedirectResponse
     *
     * @param Form $form the handled form
     * @return JsonFormResponse|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function formResponse(Form $form)
    {
        $request = $this->get('request');

        if($request->isXmlHttpRequest())
        {
            return new JsonFormResponse($form);
        } else {
            $referer = $request->headers->get('referer');
            return $this->redirect($referer);
        }
    }

}